In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load datasets from csv files into dataframes

pages_visited = pd.read_csv("pages_visited.csv")

campaigns_invested = pd.read_csv("campaigns_invested.csv")

In [3]:
# display the first few rows of pages_visited

pages_visited.head()

     page  visits  conversions
0  page 1    1000           50
1  page 2    1200           60
2  page 3     800           40
3  page 4    1500           75
4  page 5     900           45

In [4]:
# display the first few rows of campaigns_invested

campaigns_invested.head()

     campaign  investment  revenue
0  campaign 1        5000     8000
1  campaign 2        6000    10000
2  campaign 3        4000     7000
3  campaign 4        7500    12000
4  campaign 5        4500     8500

In [5]:
# display basic information about pages_visited

pages_visited.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   page         50 non-null     object
 1   visits       50 non-null     int64
 2   conversions  50 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

In [6]:
# display basic information about campaigns_invested

campaigns_invested.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   campaign    50 non-null     object
 1   investment  50 non-null     int64
 2   revenue     50 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

In [7]:
# calculate conversion rate, as a percentage, for the pages_visited data
# add the result as a new column 

pages_visited["conversion_rate"] = (pages_visited["conversions"] / pages_visited["visits"]) * 100

In [8]:
# check out the updates

pages_visited

       page  visits  conversions  conversion_rate
0    page 1    1000           50         5.000000
1    page 2    1200           60         5.000000
2    page 3     800           40         5.000000
3    page 4    1500           75         5.000000
4    page 5     900           45         5.000000
5    page 6    1100           55         5.000000
6    page 7    1300           65         5.000000
7    page 8     950           47         4.947368
8    page 9    1150           58         5.043478
9   page 10    1050           53         5.047619
10  page 11    1400           70         5.000000
11  page 12     850           42         4.941176
12  page 13    1100           55         5.000000
13  page 14    1000           50         5.000000
14  page 15    1200           60         5.000000
15  page 16    1300           65         5.000000
16  page 17    1000           50         5.000000
17  page 18     800           40         5.000000
18  page 19    1200           60         5.000000
19  page 20    1500           75         5.000000
20  page 21     950           47         4.947368
21  page 22    1150           57         4.956522
22  page 23    1050           53         5.047619
23  page 24    1400           68         4.857143
24  page 25     900           48         5.333333
25  page 26    1100           58         5.272727
26  page 27    1300           63         4.846154
27  page 28     950           45         4.736842
28  page 29    1150           57         4.956522
29  page 30    1050           52         4.952381
30  page 31    1400           69         4.928571
31  page 32     850           43         5.058824
32  page 33    1100           56         5.090909
33  page 34    1000           50         5.000000
34  page 35    1200           60         5.000000
35  page 36    1300           65         5.000000
36  page 37    1000           50         5.000000
37  page 38     800           40         5.000000
38  page 39    1200           60         5.000000
39  page 40    1500           75         5.000000
40  page 41     950           47         4.947368
41  page 42    1150           57         4.956522
42  page 43    1050           53         5.047619
43  page 44    1400           68         4.857143
44  page 45     900           48         5.333333
45  page 46    1100           58         5.272727
46  page 47    1300           63         4.846154
47  page 48     950           45         4.736842
48  page 49    1150           57         4.956522
49  page 50    1050           52         4.952381

In [9]:
# calculate return on investment, or ROI, as a percentage, for the campaigns_invested data
# add the result as a new column 

campaigns_invested["ROI"] = ((campaigns_invested["revenue"] - campaigns_invested["investment"]) / campaigns_invested["investment"]) * 100

In [10]:
# check out the updates

campaigns_invested

       campaign  investment  revenue         ROI
0    campaign 1        5000     8000   60.000000
1    campaign 2        6000    10000   66.666667
2    campaign 3        4000     7000   75.000000
3    campaign 4        7500    12000   60.000000
4    campaign 5        4500     8500   88.888889
5    campaign 6        5500     9500   72.727273
6    campaign 7        6500    11000   69.230769
7    campaign 8        4700     9200   95.744681
8    campaign 9        5800    10500   81.034483
9   campaign 10        5300     9800   84.905660
10  campaign 11        7000    13000   85.714286
11  campaign 12        4200     8700  107.142857
12  campaign 13        5500    10000   81.818182
13  campaign 14        5000     8000   60.000000
14  campaign 15        6000     9500   58.333333
15  campaign 16        6500    11000   69.230769
16  campaign 17        5000     8000   60.000000
17  campaign 18        4000     7000   75.000000
18  campaign 19        6000     9500   58.333333
19  campaign 20        7500    12000   60.000000
20  campaign 21        4700     9200   95.744681
21  campaign 22        5700    10500   84.210526
22  campaign 23        5300     9800   84.905660
23  campaign 24        6800    11500   69.117647
24  campaign 25        4800     8600   79.166667
25  campaign 26        5800    10000   72.413793
26  campaign 27        6300    11000   74.603175
27  campaign 28        4500     8400   86.666667
28  campaign 29        5700     9800   71.929825
29  campaign 30        5200     9500   82.692308
30  campaign 31        6900    11800   71.014493
31  campaign 32        4300     8900  106.976744
32  campaign 33        5600    10500   87.500000
33  campaign 34        5000     8000   60.000000
34  campaign 35        6000     9500   58.333333
35  campaign 36        6500    11000   69.230769
36  campaign 37        5000     8000   60.000000
37  campaign 38        4000     7000   75.000000
38  campaign 39        6000     9500   58.333333
39  campaign 40        7500    12000   60.000000
40  campaign 41        4700     9200   95.744681
41  campaign 42        5700    10500   84.210526
42  campaign 43        5300     9800   84.905660
43  campaign 44        6800    11500   69.117647
44  campaign 45        4800     8600   79.166667
45  campaign 46        5800    10000   72.413793
46  campaign 47        6300    11000   74.603175
47  campaign 48        4500     8400   86.666667
48  campaign 49        5700     9800   71.929825
49  campaign 50        5200     9500   82.692308