In [1]:
# import relevant libraries

import pandas as pd

In [2]:
# load data from csv file into dataframe

analytics_data = pd.read_csv("analytics_data.csv")

In [3]:
# view the data that's been loaded in

analytics_data.head()

,URL,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value
0,example1.com,813,665,0:02:05,641,14.35%,55.97%,$0.00
1,example2.com,515,388,0:02:17,373,59.25%,56.89%,$0.00
2,example3.com,336,163,0:01:06,23,10.53%,33.04%,$0.00
3,example4.com,140,120,0:02:04,73,18.31%,57.86%,$0.00
4,example5.com,136,105,0:01:30,22,14.29%,47.79%,$0.00

In [4]:
# get the current column names in analytics_data

analytics_data.columns

Index(['URL', 'Pageviews', 'Unique Pageviews', 'Avg. Time on Page',
       'Entrances', 'Bounce Rate', '% Exit', 'Page Value'],
      dtype='object')

In [5]:
# rename the columns in analytics_data as data cleaning step

analytics_data = analytics_data.rename(columns = {"URL":"url", "Pageviews":"views", "Unique Pageviews":"unique_views", "Avg. Time on Page":"avg_time", 
                                                  "Entrances":"entrances", "Bounce Rate":"bounce_rate", "% Exit":"exit_rate", "Page Value":"value"})

# display the first few rows of analytics_data after the update

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,example1.com,813,665,0:02:05,641,14.35%,55.97%,$0.00
1,example2.com,515,388,0:02:17,373,59.25%,56.89%,$0.00
2,example3.com,336,163,0:01:06,23,10.53%,33.04%,$0.00
3,example4.com,140,120,0:02:04,73,18.31%,57.86%,$0.00
4,example5.com,136,105,0:01:30,22,14.29%,47.79%,$0.00

In [6]:
# insert the missing part of the URL to every value in the "url" column 

analytics_data["url"] = "https://" + analytics_data["url"]

# display the first few rows of analytics_data after the update

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,813,665,0:02:05,641,14.35%,55.97%,$0.00
1,https://example2.com,515,388,0:02:17,373,59.25%,56.89%,$0.00
2,https://example3.com,336,163,0:01:06,23,10.53%,33.04%,$0.00
3,https://example4.com,140,120,0:02:04,73,18.31%,57.86%,$0.00
4,https://example5.com,136,105,0:01:30,22,14.29%,47.79%,$0.00