In [1]:
# import relevant libraries

import warnings
import pandas as pd

# suppress FutureWarning messages
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
# load data from csv file into dataframe

analytics_data = pd.read_csv("analytics_data_cleaned.csv")

In [3]:
# view the data that's been loaded in

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,813,665,0:02:05,641,14.35%,55.97%,$0.00
1,https://example2.com,515,388,0:02:17,373,59.25%,56.89%,$0.00
2,https://example3.com,336,163,0:01:06,23,10.53%,33.04%,$0.00
3,https://example4.com,140,120,0:02:04,73,18.31%,57.86%,$0.00
4,https://example5.com,136,105,0:01:30,22,14.29%,47.79%,$0.00

In [4]:
# check the data types in analytics_data

analytics_data.dtypes

url             object
views            int64
unique_views     int64
avg_time        object
entrances        int64
bounce_rate     object
exit_rate       object
value           object
dtype: object

In [5]:
# convert avg_time column from string to time delta

analytics_data["avg_time"] = pd.to_timedelta(analytics_data["avg_time"])

# display first few rows of analytics_data after the update

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,813,665,0 days 00:02:05,641,14.35%,55.97%,$0.00
1,https://example2.com,515,388,0 days 00:02:17,373,59.25%,56.89%,$0.00
2,https://example3.com,336,163,0 days 00:01:06,23,10.53%,33.04%,$0.00
3,https://example4.com,140,120,0 days 00:02:04,73,18.31%,57.86%,$0.00
4,https://example5.com,136,105,0 days 00:01:30,22,14.29%,47.79%,$0.00

In [6]:
# replace % with an empty string in bounce_rate

analytics_data["bounce_rate"] = analytics_data["bounce_rate"].str.replace("%","")

# convert bounce_rate column to float

analytics_data["bounce_rate"] = analytics_data["bounce_rate"].astype("float")

# display first few rows of analytics_data after the update

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,813,665,0 days 00:02:05,641,14.35,55.97%,$0.00
1,https://example2.com,515,388,0 days 00:02:17,373,59.25,56.89%,$0.00
2,https://example3.com,336,163,0 days 00:01:06,23,10.53,33.04%,$0.00
3,https://example4.com,140,120,0 days 00:02:04,73,18.31,57.86%,$0.00
4,https://example5.com,136,105,0 days 00:01:30,22,14.29,47.79%,$0.00

In [7]:
# replace % with an empty string in exit_rate

analytics_data["exit_rate"] = analytics_data["exit_rate"].str.replace("%","")

# convert exit_rate column to float

analytics_data["exit_rate"] = analytics_data["exit_rate"].astype("float")

# display first few rows of analytics_data after the update

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,813,665,0 days 00:02:05,641,14.35,55.97,$0.00
1,https://example2.com,515,388,0 days 00:02:17,373,59.25,56.89,$0.00
2,https://example3.com,336,163,0 days 00:01:06,23,10.53,33.04,$0.00
3,https://example4.com,140,120,0 days 00:02:04,73,18.31,57.86,$0.00
4,https://example5.com,136,105,0 days 00:01:30,22,14.29,47.79,$0.00

In [8]:
# replace % with an empty string in value column

analytics_data["value"] = analytics_data["value"].str.replace("$","")

# convert value column to float

analytics_data["value"] = analytics_data["value"].astype("float")

# display first few rows of analytics_data after the update

analytics_data.head()

,url,views,unique_views,avg_time,entrances,bounce_rate,exit_rate,value
0,https://example1.com,813,665,0 days 00:02:05,641,14.35,55.97,0.0
1,https://example2.com,515,388,0 days 00:02:17,373,59.25,56.89,0.0
2,https://example3.com,336,163,0 days 00:01:06,23,10.53,33.04,0.0
3,https://example4.com,140,120,0 days 00:02:04,73,18.31,57.86,0.0
4,https://example5.com,136,105,0 days 00:01:30,22,14.29,47.79,0.0